version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bicharada_db
    ports:
      - 3002:3306

  # backend:
  #   build: backend/.
  #   user: node
  #   working_dir: /app
  #   container_name: hey_bicharada_api
  #   tty: true
  #   stdin_open: true
  #   command: bash
  #   restart: always
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 3001:3001
