export default {
  backgrounds: {
    one: require('../assets/backgrounds/01.png'),
    two: require('../assets/backgrounds/02.png'),
    tree: require('../assets/backgrounds/03.png'),
    four: require('../assets/backgrounds/04.png'),
    five: require('../assets/backgrounds/05.png'),
    six: require('../assets/backgrounds/06.png'),
  },
  donate: require('../assets/donate.png'),
  piggy: require('../assets/piggy.png'),
  logo: require('../assets/logo.png'),
  arrow: require('../assets/arrow.png'),
  plus: require('../assets/plus.png'),
  camera: require('../assets/camera.png'),
  folder: require('../assets/folder.png'),
  spLogo: require('../assets/brasao.png'),
  checked: require('../assets/checked.png'),
  enviar: require('../assets/enviar.png'),
  logout: require('../assets/logout.png'),
};
