export const Rifas = [
     {id: 1, name: 'Colera Cat Dog', entrance: 20.00, picture: 'https://atespets.com.br/products/colar_cat_dog.jpeg'},
     {id: 2, name: 'Luva Escova', entrance: 25.00, picture: 'https://atespets.com.br/products/luva_escova.jpeg'}
]

export const Rifa = [
     {id: 1, email: '', status: 'unavailable'},
     {id: 2, email: '', status: 'unavailable'},
     {id: 3, email: '', status: 'unavailable'},
     {id: 4, email: '', status: 'checking'},
     {id: 5, email: '', status: 'available'},
     {id: 6, email: '', status: 'available'},
     {id: 7, email: '', status: 'available'},
     {id: 8, email: '', status: 'available'},
     {id: 9, email: '', status: 'checking'},
     {id: 10, email: '', status: 'available'},
     {id: 11, email: '', status: 'available'},
     {id: 12, email: '', status: 'available'},
     {id: 13, email: '', status: 'available'},
     {id: 14, email: '', status: 'available'},
     {id: 15, email: '', status: 'available'},
     {id: 16, email: '', status: 'available'},
     {id: 17, email: '', status: 'available'},
     {id: 18, email: '', status: 'checking'},
     {id: 19, email: '', status: 'available'},
     {id: 20, email: '', status: 'available'},
     {id: 21, email: '', status: 'available'},
     {id: 22, email: '', status: 'checking'},
     {id: 23, email: '', status: 'available'},
     {id: 24, email: '', status: 'available'},
     {id: 25, email: '', status: 'available'},
     {id: 26, email: '', status: 'available'},
     {id: 27, email: '', status: 'available'},
     {id: 28, email: '', status: 'unavailable'},
     {id: 29, email: '', status: 'available'},
     {id: 30, email: '', status: 'unavailable'},
     {id: 31, email: '', status: 'available'},
     {id: 32, email: '', status: 'available'},
     {id: 33, email: '', status: 'available'},
     {id: 34, email: '', status: 'available'},
     {id: 35, email: '', status: 'available'},
     {id: 36, email: '', status: 'available'},
     {id: 37, email: '', status: 'available'},
     {id: 38, email: '', status: 'available'},
     {id: 39, email: '', status: 'available'},
     {id: 40, email: '', status: 'available'},
     {id: 41, email: '', status: 'available'},
     {id: 42, email: '', status: 'available'},
     {id: 43, email: '', status: 'available'},
     {id: 44, email: '', status: 'available'},
     {id: 45, email: '', status: 'available'},
     {id: 46, email: '', status: 'available'},
     {id: 47, email: '', status: 'available'},
     {id: 48, email: '', status: 'unavailable'},
     {id: 49, email: '', status: 'available'},
     {id: 50, email: '', status: 'available'},

]