# name: Deploy Backend to VPS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           path: backend # Defina o caminho para o diretório "backend"

#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /home/hey_pet_api
#             git pull
#         env:
#           SSH_AUTH_SOCK: ${{ secrets.SSH_AUTH_SOCK }}
